'use client';
import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { api, NodeDetails } from '../../../../lib/api';
import { PageHeader, Card, Badge, Alert, Spinner, colors } from '../../../../lib/ui';

function formatBytes(value?: string | null) { if (!value) return '—'; let n = Number(value); const u = ['B', 'KB', 'MB', 'GB']; let i = 0; while (n >= 1024 && i < 3) { n /= 1024; i++; } return `${n.toFixed(i ? 1 : 0)} ${u[i]}`; }
function age(value?: string) { if (!value) return 'Never'; const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); return seconds < 60 ? `${seconds}s ago` : seconds < 3600 ? `${Math.floor(seconds / 60)}m ago` : `${Math.floor(seconds / 3600)}h ago`; }

export default function AdminNodeDetailPage() {
  const { id } = useParams<{ id: string }>(); const [node, setNode] = useState<NodeDetails | null>(null); const [error, setError] = useState('');
  const load = () => api.nodes.get(id).then(setNode).catch((e) => setError(e instanceof Error ? e.message : 'Failed to load node'));
  useEffect(() => { load(); const timer = setInterval(load, 15000); return () => clearInterval(timer); }, [id]);
  if (error && !node) return <Alert message={error} />; if (!node) return <Spinner />;
  const last = node.heartbeats?.[0]; const metric = node.metrics?.[0]; const healthy = node.status === 'healthy' || (last && Date.now() - new Date(last.reportedAt).getTime() < 60000);
  return <div><Link href="/admin/nodes" style={{ color: colors.textMuted, fontSize: 13, textDecoration: 'none' }}>← Back to nodes</Link><PageHeader title={node.label} action={<button onClick={load} style={{ padding: '8px 14px', border: `1px solid ${colors.border}`, borderRadius: 7, background: '#f8fafc', cursor: 'pointer' }}>Refresh</button>} />
    <Card style={{ padding: 20, marginBottom: 18, border: `1px solid ${healthy ? '#bbf7d0' : '#fecaca'}`, background: healthy ? '#f0fdf4' : '#fff7f7' }}><div style={{ display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' }}><Badge label={healthy ? 'healthy' : node.status} /><strong>{node.country?.name ?? node.countryCode}</strong><span style={{ color: colors.textMuted }}>{node.ipv4Address ?? node.ipv6Address ?? 'IP pending'}</span><span style={{ color: colors.textMuted, fontSize: 12 }}>Heartbeat: {age(last?.reportedAt)}</span></div></Card>
    <Card style={{ padding: 20, marginBottom: 18 }}><h2 style={{ margin: '0 0 16px', fontSize: 17, color: colors.navy }}>System information</h2><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(180px,1fr))', gap: 14 }}>{[['Hostname', node.hostname], ['Operating system', node.osName], ['Architecture', node.architecture], ['CPU cores', node.cpuCores], ['Memory', formatBytes(node.memoryBytes)], ['Uptime', node.uptimeSeconds ? `${Math.floor(Number(node.uptimeSeconds) / 3600)}h` : null], ['IPv4', node.ipv4Address], ['IPv6', node.ipv6Address], ['Reported country', node.reportedCountry], ['Config version', node.configVersion]].map(([label, value]) => <div key={String(label)}><div style={{ color: colors.textMuted, fontSize: 11, marginBottom: 4 }}>{label}</div><strong style={{ direction: label === 'IPv4' || label === 'IPv6' ? 'ltr' : undefined }}>{value ?? 'Not reported'}</strong></div>)}</div></Card>
    <Card style={{ padding: 20, marginBottom: 18 }}><h2 style={{ margin: '0 0 16px', fontSize: 17, color: colors.navy }}>Live resource usage</h2><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(160px,1fr))', gap: 14 }}>{[['CPU', metric?.cpuPct ? `${metric.cpuPct}%` : 'Not reported'], ['Memory', metric?.memPct ? `${metric.memPct}%` : 'Not reported'], ['Active sessions', metric?.activeSessions ?? 'Not reported'], ['Last metric', age(metric?.recordedAt)]].map(([label, value]) => <div key={String(label)} style={{ padding: 14, border: `1px solid ${colors.border}`, borderRadius: 8 }}><div style={{ color: colors.textMuted, fontSize: 12 }}>{label}</div><strong style={{ display: 'block', marginTop: 6 }}>{value}</strong></div>)}</div></Card>
    <Card style={{ padding: 20 }}><h2 style={{ margin: '0 0 16px', fontSize: 17, color: colors.navy }}>Connectivity & capabilities</h2><div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 14 }}>{node.roles.map((role) => <Badge key={role} label={role} />)}{node.capabilities.map((cap) => <Badge key={`${cap.protocol}-${cap.transport}`} label={`${cap.protocol}:${cap.port}`} />)}</div><div style={{ color: colors.textMuted, fontSize: 12 }}>Agent: {last?.agentVersion ?? 'Not reported'} · Last heartbeat: {last ? new Date(last.reportedAt).toLocaleString() : 'Never'} · Health checks recorded: {node.healthChecks?.length ?? 0}</div></Card>
  </div>;
}
