ALTER TABLE "nodes" ADD COLUMN IF NOT EXISTS "hostname" TEXT;
ALTER TABLE "nodes" ADD COLUMN IF NOT EXISTS "os_name" TEXT;
ALTER TABLE "nodes" ADD COLUMN IF NOT EXISTS "architecture" TEXT;
ALTER TABLE "nodes" ADD COLUMN IF NOT EXISTS "cpu_cores" INTEGER;
ALTER TABLE "nodes" ADD COLUMN IF NOT EXISTS "memory_bytes" BIGINT;
ALTER TABLE "nodes" ADD COLUMN IF NOT EXISTS "uptime_seconds" BIGINT;
